version: "3"

services:

  gateway:
    image:  192.168.99.100:5000/gateway-service:latest
    container_name: gateway
    ports:
      - "8001:8001"
    networks:
      - test
    depends_on:
      - nacos
    links:
      - nacos:myNacos

  nacos:
    image:  nacos/nacos-server
    container_name: myNacos
    ports:
      - "8848:8848"
    networks:
      - test
    environment:
      - "MODE=standalone"


networks:
   test:
     driver: bridge