server:
  port: 8001
spring:
  application:
    name: gateway
  profiles:
    active: dev
#    上面2个配置 和bootstrap中的配置意味着会去读取 指定命名空间下的 gateway-dev.yaml 配置文件
  cloud:
    gateway:
      routes:
      - id: testService
        uri: lb://testService
        predicates:
        - Path=/testService/**
        filters:
        - RewritePath=/testSerivce/(?<path>.*), /$\{path}

