server:
  port: 8003
spring:
  application:
    name: user

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://my:7777/testSpring?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
seata:
  tx-service-group: my_test_tx_group
  registry:
    type: nacos #nacos
    nacos:
      application: seata-server
      server-addr: mySeata:8848
  config:
    type: nacos
    nacos:
      server-addr: mySeata:8848
      group: SEATA_GROUP
  service:
    vgroup-mapping:
      my_test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: true
    undo:
      log-table: undo_log
      log-serialization: jackson
      data-validation: true


rocketmq:
  consumer:
    groupName: ${spring.application.name}
    namesrvAddr:  127.0.0.1:9876
    topics: userTopic~*
    consumeThreadMin: 5
    consumeThreadMax: 32
    consumeMessageBatchMaxSize: 1


#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: top.fan2wan.user.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    #capital-mode: true
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false